name: Django Accounting CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set environment variables
      uses: krisalay/export-env@v1.0.0
      with:
        filename: config.test.env
    - name: Run Tests
      run: |
        printenv

